[workspace]
members = [
    "elements-harness",
    "swap",
    "bobtimus",
    "extension",
    "extension/wallet_lib",
    "extension/background",
    "extension/content",
    "extension/in_page",
    "extension/wasm_bindgen_extension"
]

[patch.crates-io]
# Until https://github.com/ElementsProject/rust-elements/pull/70/ is merged
elements = { git = "https://github.com/luckysori/rust-elements", branch = "upstreaming-fun" }
