version: '3'
services:
  # RPC daemons
  liquid:
    image: blockstream/elementsd:0.18.1.9
    container_name: liquid-e2e-test
    entrypoint:
      - elementsd
    command:
      - -chain=liquidregtest
      - -txindex=1
      - -listen=1
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcport=18884
      - -printtoconsole
      - -rest
      - -validatepegin=0
      - -blindedaddresses=1
      - -initialfreecoins=2100000000000000
      - -rpcuser=admin1
      - -rpcpassword=123
      - -port=18886
      - -datadir=/data
    networks:
      local:
        ipv4_address: 11.10.0.11
    ports:
      - 7041:18884
    volumes:
      - blockchain_volume:/data
    restart: unless-stopped
  # Block explorer REST servers
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvvv
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - 11.10.0.11:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    networks:
      local:
        ipv4_address: 11.10.0.13
    depends_on:
      - liquid
    ports:
      - 60401:60401
      - 3012:3002
    volumes:
      - blockchain_volume:/config
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    networks:
      local:
        ipv4_address: 11.10.0.15
    depends_on:
      - electrs-liquid
    environment:
      API_URL: http://localhost:3012
    ports:
      - 5001:5000

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 11.10.0.0/24

volumes:
  blockchain_volume:
